# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/duty_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DutyWindow(object):
    def setupUi(self, DutyWindow):
        DutyWindow.setObjectName("DutyWindow")
        DutyWindow.resize(750, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DutyWindow.sizePolicy().hasHeightForWidth())
        DutyWindow.setSizePolicy(sizePolicy)
        DutyWindow.setMinimumSize(QtCore.QSize(600, 500))
        DutyWindow.setMaximumSize(QtCore.QSize(750, 600))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        DutyWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(DutyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.allow_btn = QtWidgets.QPushButton(self.centralwidget)
        self.allow_btn.setGeometry(QtCore.QRect(80, 500, 240, 60))
        self.allow_btn.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.allow_btn.setObjectName("allow_btn")
        self.forbid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.forbid_btn.setGeometry(QtCore.QRect(420, 500, 240, 60))
        self.forbid_btn.setStyleSheet("background-color: red;\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.forbid_btn.setObjectName("forbid_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 30, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 240, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 141, 20))
        self.label_3.setObjectName("label_3")
        self.new_car = QtWidgets.QLabel(self.centralwidget)
        self.new_car.setGeometry(QtCore.QRect(40, 450, 581, 31))
        self.new_car.setObjectName("new_car")
        self.clean_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clean_btn.setGeometry(QtCore.QRect(630, 440, 101, 41))
        self.clean_btn.setStyleSheet("background-color:rgb(217, 0, 0);\n"
"border-radius: 10px;\n"
"color: white;\n"
"font-size: 16px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../../Desktop/DIPLOMA/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clean_btn.setIcon(icon)
        self.clean_btn.setObjectName("clean_btn")
        self.all_cars = QtWidgets.QListWidget(self.centralwidget)
        self.all_cars.setGeometry(QtCore.QRect(20, 60, 311, 371))
        self.all_cars.setObjectName("all_cars")
        self.departed_cars = QtWidgets.QListWidget(self.centralwidget)
        self.departed_cars.setGeometry(QtCore.QRect(350, 60, 381, 171))
        self.departed_cars.setObjectName("departed_cars")
        self.arrived_cars = QtWidgets.QListWidget(self.centralwidget)
        self.arrived_cars.setGeometry(QtCore.QRect(350, 270, 381, 161))
        self.arrived_cars.setObjectName("arrived_cars")
        self.depart_amount = QtWidgets.QLabel(self.centralwidget)
        self.depart_amount.setGeometry(QtCore.QRect(430, 20, 31, 41))
        self.depart_amount.setObjectName("depart_amount")
        self.arrive_amount = QtWidgets.QLabel(self.centralwidget)
        self.arrive_amount.setGeometry(QtCore.QRect(450, 230, 31, 41))
        self.arrive_amount.setObjectName("arrive_amount")
        self.cars_amount = QtWidgets.QLabel(self.centralwidget)
        self.cars_amount.setGeometry(QtCore.QRect(160, 20, 31, 41))
        self.cars_amount.setObjectName("cars_amount")
        DutyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DutyWindow)
        QtCore.QMetaObject.connectSlotsByName(DutyWindow)

    def retranslateUi(self, DutyWindow):
        _translate = QtCore.QCoreApplication.translate
        DutyWindow.setWindowTitle(_translate("DutyWindow", "Дежурный по части"))
        self.allow_btn.setText(_translate("DutyWindow", "Разрешить"))
        self.forbid_btn.setText(_translate("DutyWindow", "Запретить"))
        self.label.setText(_translate("DutyWindow", "Убыли:"))
        self.label_2.setText(_translate("DutyWindow", "Прибыли:"))
        self.label_3.setText(_translate("DutyWindow", "Общий список:"))
        self.new_car.setText(_translate("DutyWindow", "* Новых машин нет"))
        self.clean_btn.setText(_translate("DutyWindow", "Очистить"))
        self.depart_amount.setText(_translate("DutyWindow", "0"))
        self.arrive_amount.setText(_translate("DutyWindow", "0"))
        self.cars_amount.setText(_translate("DutyWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DutyWindow = QtWidgets.QMainWindow()
    ui = Ui_DutyWindow()
    ui.setupUi(DutyWindow)
    DutyWindow.show()
    sys.exit(app.exec_())
