# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diploma_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(600, 500))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arrive_btn = QtWidgets.QPushButton(self.centralwidget)
        self.arrive_btn.setGeometry(QtCore.QRect(50, 400, 240, 60))
        self.arrive_btn.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.arrive_btn.setObjectName("arrive_btn")
        self.depart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.depart_btn.setGeometry(QtCore.QRect(300, 400, 240, 60))
        self.depart_btn.setStyleSheet("background-color: red;\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.depart_btn.setObjectName("depart_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 170, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 141, 20))
        self.label_3.setObjectName("label_3")
        self.new_car = QtWidgets.QLabel(self.centralwidget)
        self.new_car.setGeometry(QtCore.QRect(70, 349, 421, 31))
        self.new_car.setObjectName("new_car")
        self.clean_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clean_btn.setGeometry(QtCore.QRect(530, 350, 41, 41))
        self.clean_btn.setStyleSheet("background-color:rgb(217, 0, 0);\n"
"border-radius: 10px;")
        self.clean_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/DIPLOMA/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clean_btn.setIcon(icon)
        self.clean_btn.setObjectName("clean_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 460, 501, 41))
        self.label_4.setObjectName("label_4")
        self.all_cars = QtWidgets.QListWidget(self.centralwidget)
        self.all_cars.setGeometry(QtCore.QRect(15, 41, 281, 301))
        self.all_cars.setObjectName("all_cars")
        self.depart_cars = QtWidgets.QListWidget(self.centralwidget)
        self.depart_cars.setGeometry(QtCore.QRect(320, 40, 261, 121))
        self.depart_cars.setObjectName("depart_cars")
        self.arrived_cars = QtWidgets.QListWidget(self.centralwidget)
        self.arrived_cars.setGeometry(QtCore.QRect(320, 210, 261, 131))
        self.arrived_cars.setObjectName("arrived_cars")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 0, 31, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 160, 31, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 0, 31, 41))
        self.label_7.setObjectName("label_7")
        self.open_dialog = QtWidgets.QPushButton(self.centralwidget)
        self.open_dialog.setGeometry(QtCore.QRect(200, 10, 91, 23))
        self.open_dialog.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"font-size: 14px;")
        self.open_dialog.setObjectName("open_dialog")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "СКУД КТП"))
        self.arrive_btn.setText(_translate("MainWindow", "Прибыл"))
        self.depart_btn.setText(_translate("MainWindow", "Убыл"))
        self.label.setText(_translate("MainWindow", "Убыли:"))
        self.label_2.setText(_translate("MainWindow", "Прибыли:"))
        self.label_3.setText(_translate("MainWindow", "Общий список:"))
        self.new_car.setText(_translate("MainWindow", "* Новых машин нет"))
        self.label_4.setText(_translate("MainWindow", "Оразбекулы Ерлан 594 гр. (Кибербезопасность) 2022 год"))
        self.label_5.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.open_dialog.setText(_translate("MainWindow", "Добавить"))





