# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/list_cars.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListCars(object):
    def setupUi(self, ListCars):
        ListCars.setObjectName("ListCars")
        ListCars.resize(683, 455)
        self.centralwidget = QtWidgets.QWidget(ListCars)
        self.centralwidget.setObjectName("centralwidget")
        self.all_cars = QtWidgets.QListWidget(self.centralwidget)
        self.all_cars.setGeometry(QtCore.QRect(10, 50, 371, 361))
        self.all_cars.setObjectName("all_cars")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cars_amount = QtWidgets.QLabel(self.centralwidget)
        self.cars_amount.setGeometry(QtCore.QRect(180, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.cars_amount.setFont(font)
        self.cars_amount.setObjectName("cars_amount")
        self.num_input = QtWidgets.QTextEdit(self.centralwidget)
        self.num_input.setGeometry(QtCore.QRect(400, 160, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.num_input.setFont(font)
        self.num_input.setObjectName("num_input")
        self.model_input = QtWidgets.QTextEdit(self.centralwidget)
        self.model_input.setGeometry(QtCore.QRect(400, 80, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.model_input.setFont(font)
        self.model_input.setObjectName("model_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 120, 71, 31))
        self.label_3.setStyleSheet("font-size: 18px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 71, 31))
        self.label_4.setStyleSheet("font-size: 18px;")
        self.label_4.setObjectName("label_4")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(400, 239, 201, 41))
        self.add_btn.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font-size: 20px;\n"
"color: white;\n"
"border-radius: 15px;")
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(400, 319, 201, 41))
        self.delete_btn.setStyleSheet("background-color: red;\n"
"font-size: 20px;\n"
"color: white;\n"
"border-radius: 15px;")
        self.delete_btn.setObjectName("delete_btn")
        ListCars.setCentralWidget(self.centralwidget)

        self.retranslateUi(ListCars)
        QtCore.QMetaObject.connectSlotsByName(ListCars)

    def retranslateUi(self, ListCars):
        _translate = QtCore.QCoreApplication.translate
        ListCars.setWindowTitle(_translate("ListCars", "Список техники"))
        self.label.setText(_translate("ListCars", "Общий список:"))
        self.cars_amount.setText(_translate("ListCars", "0"))
        self.label_3.setText(_translate("ListCars", "Номер:"))
        self.label_4.setText(_translate("ListCars", "Модель:"))
        self.add_btn.setText(_translate("ListCars", "Добавить"))
        self.delete_btn.setText(_translate("ListCars", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListCars = QtWidgets.QMainWindow()
    ui = Ui_ListCars()
    ui.setupUi(ListCars)
    ListCars.show()
    sys.exit(app.exec_())
