# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/park_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParkWindow(object):
    def setupUi(self, ParkWindow):
        ParkWindow.setObjectName("ParkWindow")
        ParkWindow.resize(750, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParkWindow.sizePolicy().hasHeightForWidth())
        ParkWindow.setSizePolicy(sizePolicy)
        ParkWindow.setMinimumSize(QtCore.QSize(600, 500))
        ParkWindow.setMaximumSize(QtCore.QSize(750, 600))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        ParkWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ParkWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arrive_btn = QtWidgets.QPushButton(self.centralwidget)
        self.arrive_btn.setGeometry(QtCore.QRect(80, 480, 240, 60))
        self.arrive_btn.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.arrive_btn.setObjectName("arrive_btn")
        self.depart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.depart_btn.setGeometry(QtCore.QRect(420, 480, 240, 60))
        self.depart_btn.setStyleSheet("background-color: red;\n"
"font-size: 25px;\n"
"color: white;\n"
"border-radius: 30px;")
        self.depart_btn.setObjectName("depart_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 10, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 220, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 141, 20))
        self.label_3.setObjectName("label_3")
        self.new_car = QtWidgets.QLabel(self.centralwidget)
        self.new_car.setGeometry(QtCore.QRect(40, 430, 581, 31))
        self.new_car.setObjectName("new_car")
        self.all_cars = QtWidgets.QListWidget(self.centralwidget)
        self.all_cars.setGeometry(QtCore.QRect(20, 40, 311, 371))
        self.all_cars.setObjectName("all_cars")
        self.departed_cars = QtWidgets.QListWidget(self.centralwidget)
        self.departed_cars.setGeometry(QtCore.QRect(350, 40, 381, 171))
        self.departed_cars.setObjectName("departed_cars")
        self.arrived_cars = QtWidgets.QListWidget(self.centralwidget)
        self.arrived_cars.setGeometry(QtCore.QRect(350, 250, 381, 161))
        self.arrived_cars.setObjectName("arrived_cars")
        self.depart_amount = QtWidgets.QLabel(self.centralwidget)
        self.depart_amount.setGeometry(QtCore.QRect(430, 0, 31, 41))
        self.depart_amount.setObjectName("depart_amount")
        self.arrive_amount = QtWidgets.QLabel(self.centralwidget)
        self.arrive_amount.setGeometry(QtCore.QRect(450, 210, 31, 41))
        self.arrive_amount.setObjectName("arrive_amount")
        self.cars_amount = QtWidgets.QLabel(self.centralwidget)
        self.cars_amount.setGeometry(QtCore.QRect(160, 0, 31, 41))
        self.cars_amount.setObjectName("cars_amount")
        self.dep_count = QtWidgets.QTextEdit(self.centralwidget)
        self.dep_count.setGeometry(QtCore.QRect(280, 560, 41, 31))
        self.dep_count.setObjectName("dep_count")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 550, 221, 41))
        self.label_4.setObjectName("label_4")
        ParkWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ParkWindow)
        QtCore.QMetaObject.connectSlotsByName(ParkWindow)

    def retranslateUi(self, ParkWindow):
        _translate = QtCore.QCoreApplication.translate
        ParkWindow.setWindowTitle(_translate("ParkWindow", "Дежурный по парку"))
        self.arrive_btn.setText(_translate("ParkWindow", "Прибыл"))
        self.depart_btn.setText(_translate("ParkWindow", "Убыл"))
        self.label.setText(_translate("ParkWindow", "Убыли:"))
        self.label_2.setText(_translate("ParkWindow", "Прибыли:"))
        self.label_3.setText(_translate("ParkWindow", "Общий список:"))
        self.new_car.setText(_translate("ParkWindow", "* Новых машин нет"))
        self.depart_amount.setText(_translate("ParkWindow", "0"))
        self.arrive_amount.setText(_translate("ParkWindow", "0"))
        self.cars_amount.setText(_translate("ParkWindow", "0"))
        self.label_4.setText(_translate("ParkWindow", "Количество убывающих:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ParkWindow = QtWidgets.QMainWindow()
    ui = Ui_ParkWindow()
    ui.setupUi(ParkWindow)
    ParkWindow.show()
    sys.exit(app.exec_())
